printWidth: 120 #строки не длиннее
trailingComma: es5 # правило определяющее где нужны запятые (es5 - ставить везде где можно)
tabWidth: 4 # величина таба
semi: false # нет точек с запятой
singleQuote: true # кавычки одинарные
